### ISSUE TITLE
Execute Errors

### ISSUE THREAD

**Issue by Keelan** [JohnMcLear/Transfer-Video-from-Youtube-to-Vimeo#10]
When i run this i get:

> youtube_username Setting is NOT SET

Even though it is. So i edited testSettings from:

``` php
  if($settings["youtube_username"] = "" || $settings["youtube_username"] = "meh"){
```

to

``` php
  if($settings["youtube_username"] = ""){
```

Now because i am running it in test mode before i run this. I get this in my error log?

> [06-Apr-2015 13:59:13 America/New_York] PHP Fatal error:  Call to undefined function stdout() in 
> /home/feefifofail/public_html/xtransfer/include/testSettings.php on line 23

To get this to work i had to change:

``` php
stdout("Running in debug only mode");
```

to:

``` php
$stdout = "Running in debug only mode";
```

Also i noticed that alt codes are lost, i use ♥ ►◄ and similar. They are lost when importing them to the description variable. I thought maybe it was a font issue but doesn't seem to be.

Changed:

``` php
<?php
require_once('config.php');
require_once('include/curlFunctions.php');
require_once('include/youtubeFunctions.php');
require_once('include/testSettings.php');
```

to:

``` php
<?php
header('Content-Type: text/html; charset=utf-8');
require_once('config.php');
require_once('include/curlFunctions.php');
require_once('include/youtubeFunctions.php');
require_once('include/testSettings.php');
```

**Comment by JohnMcLear** [comment]
I didn't even think this script would still work.

I'm not actively maintaining it.  If you want to fork and maintain that is fine with me, I can redirect people to your branch! :)

**Comment by Keelan** [comment]
I haven't gone much further than testing so i am not sure if it will authenticate correctly with vimeo. Plus vimeo's restrictions are extreme 500 mb a week for free users.

I will take a look see if i can get it working first.

Thanks for the update.
